import * as React from "react";
import Card from "@mui/material/Card";
import Chip from "@mui/material/Chip";
import CardMedia from "@mui/material/CardMedia";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";

import Chorizo from "../../static/images/Chorizo.jpg";
import AIawwBG from "../../static/images/AIawwBG.png";

// temp dummy data
let recipeImage = null;
const ingredients = [
  "1 cup of flour",
  "2 eggs",
  "1/2 cup of sugar",
  "1 cup of milk",
];

const instructions = [
  "Step 1: Do something",
  "Step 2: Do something else",
  "Step 3: Continue doing things",
  "Step 4: Almost there",
  "Step 5: Finished",
];
// end temp dummy data


function Home() {
  const [recipeNameInput, setRecipeNameInput] = React.useState(null);
  const [recipeName, setRecipeName] = React.useState(null);

  const handleInputChange = (event) => {
    setRecipeNameInput(event.target.value);
  };

  const handleButtonClick = (event) => {
    setRecipeName(recipeNameInput);
  };

  return (
    <Box
      sx={{
        position: "absolute",
        paddingTop: "90px",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        backgroundImage: `url(${AIawwBG})`,
        backgroundSize: "cover",
        opacity: 1,
      }}
    >
      <TextField
        label="Enter recipe name"
        value={recipeNameInput || ""}
        onChange={handleInputChange}
        onKeyUp={(event) => {
          if (event.key === "Enter") {
            handleButtonClick();
          }
        }}
        variant="outlined"
        color="secondary"
        sx={{ marginBottom: 2 }}
      />
      <Button variant="contained" color="secondary" onClick={handleButtonClick}>
        Enter
      </Button>
      <Typography
        variant="h4"
        component="h2"
        color="var(--secondary-color)"
        sx={{ marginTop: 2 }}
      >
        {recipeName || "Recipe Name"}
      </Typography>
      <Card sx={{ maxWidth: 600, margin: 2 }}>
        {recipeImage ? (
          <CardMedia
            component="img"
            image={recipeImage}
            alt="recipe dish image"
          />
        ) : (
          <CardContent
            sx={{
              backgroundColor: "#FFFFFF",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              minHeight: 400,
              minWidth: 400,
            }}
          >
            <Typography variant="body1" color="text.secondary">
              Image that will be Generated By DALL-E
            </Typography>
          </CardContent>
        )}
      </Card>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          flexWrap: "wrap",
          listStyle: "none",
          padding: 1,
          margin: 0,
        }}
      >
        {ingredients.map((ingredient, index) => {
          return (
            <Box key={index} sx={{ margin: 1 }}>
              <Chip
                label={ingredient}
                sx={{
                  fontWeight: "bold",
                  fontFamily: "Arial",
                }}
              />
            </Box>
          );
        })}
      </Box>
      <Typography 
        variant="h5" 
        component="h2"
        color="var(--secondary-color)"
        sx={{ marginTop: 2 }}
      >
        Instructions
      </Typography>
      <List>
        {instructions.map((instruction, index) => {
          return (
            <ListItem key={index}>
              <Typography>{instruction}</Typography>
            </ListItem>
          );
        })}
      </List>
    </Box>
  );
}

export default Home;
